import {writeU16LE,writeU32LE} from './bytes'; import {encodeRleV1,encodeRleV2} from './rle';
const MAGIC=Uint8Array.of(0xe0,0x21,0xa5,0x5a), HEADER=12, PALETTE=1024;
export type Raster={rgba:Uint8Array,width:number,height:number};
const colorKey=(d:Uint8Array,o:number)=>((((d[o+3]??0)<<24)|((d[o]??0)<<16)|((d[o+1]??0)<<8)|(d[o+2]??0))>>>0);
function indexed(rgba:Uint8Array){const p=new Map<number,number>(),idx=new Uint8Array(rgba.length/4);for(let o=0,n=0;o<rgba.length;o+=4,n++){const k=colorKey(rgba,o);let i=p.get(k);if(i===undefined){if(p.size===256)return;i=p.size;p.set(k,i)}idx[n]=i}const out=new Uint8Array(PALETTE+idx.length);for(const[k,i]of p){const o=i*4;out[o]=k&255;out[o+1]=(k>>>8)&255;out[o+2]=(k>>>16)&255;out[o+3]=(k>>>24)&255}out.set(idx,PALETTE);return out}
function bgra(r:Uint8Array){const o=new Uint8Array(r.length);for(let i=0;i<r.length;i+=4){o[i]=r[i+2];o[i+1]=r[i+1];o[i+2]=r[i];o[i+3]=r[i+3]}return o}
function payload(raw:Uint8Array,bpp:number,pal:boolean){const enc=pal?encodeRleV2(raw):encodeRleV1(raw,bpp),o=new Uint8Array(8+enc.length);o.set(MAGIC);writeU32LE(o,4,(raw.length<<4)|bpp);o.set(enc,8);return o}
export function encodeImage(img:Raster){const ind=indexed(img.rgba),raw=ind??bgra(img.rgba),pay=payload(raw,ind?1:4,!!ind),h=new Uint8Array(HEADER);h[0]=ind?0x10:0;h[1]=4;writeU16LE(h,4,img.width);writeU16LE(h,6,img.height);writeU32LE(h,8,pay.length);return concat([h,pay])}
export function encodeList(images:Raster[]){if(!images.length||images.length>255)throw Error('Lista de imágenes inválida');const {width,height}=images[0];if(images.some(i=>i.width!==width||i.height!==height))throw Error('Todos los dígitos deben medir lo mismo');const inds=images.map(i=>indexed(i.rgba)),pal=inds.every(Boolean),ps=images.map((i,n)=>payload((pal?inds[n]:undefined)??bgra(i.rgba),pal?1:4,pal));const len=ps.reduce((a,p)=>a+p.length,ps.length*4),out=new Uint8Array(HEADER+len);out[0]=pal?0x10:0;out[1]=images.length;out[2]=4;writeU16LE(out,4,width);writeU16LE(out,6,height);writeU32LE(out,8,len);let off=HEADER+ps.length*4;ps.forEach((p,i)=>{writeU32LE(out,HEADER+i*4,p.length);out.set(p,off);off+=p.length});return out}
export function concat(parts:Uint8Array[]){const o=new Uint8Array(parts.reduce((a,p)=>a+p.length,0));let n=0;for(const p of parts){o.set(p,n);n+=p.length}return o}
