import {writeFixedString,writeU16LE,writeU24LE,writeU32LE,readU16LE,readU32LE,readNullTerminated,toHex} from './bytes';
import {concat,encodeImage,encodeList,type Raster} from './imageCodec'; import {digits,preview,solid,textRaster} from './raster'; import type{Design}from'./schema';
const MAIN=0xa8,FACE=0x58,DEF=16;type Elem={x:number,y:number,type:'image'|'num',src?:string,digits?:Raster[],count?:number,data?:string,align?:number,space?:number,zero?:boolean};type Resource={block:Uint8Array};
const u=(b:Uint8Array,o:number,c:number,t:number)=>{writeU32LE(b,o,c);writeU32LE(b,o+4,t)};
function data(b:Uint8Array,o:number,s?:string){if(!s)return;const a=(s.match(/../g)||[]).map(v=>parseInt(v,16));b.set(a.slice(0,3),o)}
function prepare(elems:Elem[]){const singles:Resource[]=[],lists:Resource[]=[],singleMap=new Map<string,number>(),listMap=new Map<string,number>();const refs:{e:Elem,t:number,i:number}[]=[];const single=(k:string,img:Raster)=>{if(singleMap.has(k))return singleMap.get(k)!;const i=singles.length;singleMap.set(k,i);singles.push({block:encodeImage(img)});return i};const list=(k:string,imgs:Raster[])=>{if(listMap.has(k))return listMap.get(k)!;const i=lists.length;listMap.set(k,i);lists.push({block:encodeList(imgs)});return i};for(const e of elems){if(e.type==='image')refs.push({e,t:2,i:single(e.src!,e.digits![0])});else refs.push({e,t:7,i:refs.filter(r=>r.t===7).length})}const widgets=refs.filter(r=>r.t===7).map(r=>({e:r.e,list:list('digits-'+(r.e.digits?.[0].width||0)+'-'+r.e.data,r.e.digits!)}));return{refs,singles,lists,widgets,definition:(refs.length+singles.length+lists.length+widgets.length)*DEF,property:refs.length*16+widgets.length*20}}
function head(p:ReturnType<typeof prepare>,start:number,previewOff:number){const h=new Uint8Array(FACE);writeU32LE(h,4,previewOff);let o=start;u(h,8,p.refs.length,o);o+=p.refs.length*DEF;u(h,0x10,0,o);u(h,0x18,p.singles.length,o);o+=p.singles.length*DEF;u(h,0x20,p.lists.length,o);o+=p.lists.length*DEF;u(h,0x28,0,o);u(h,0x30,0,o);u(h,0x38,0,o);u(h,0x40,p.widgets.length,o);o+=p.widgets.length*DEF;u(h,0x48,0,o);u(h,0x50,0,o);return h}
function def(b:Uint8Array,o:number,i:number,t:number,target:number,len:number){writeU16LE(b,o,i);b[o+3]=t;writeU32LE(b,o+8,target);writeU32LE(b,o+12,len)}
function offsets(rs:Resource[],start:number){const out:number[]=[];for(const r of rs){out.push(start);start+=r.block.length}return out}
function faceData(p:ReturnType<typeof prepare>,propStart:number,sing:number[],lists:number[]){const out=new Uint8Array(p.definition+p.property);let d=0,po=p.definition,abs=propStart;for(let i=0;i<p.refs.length;i++){def(out,d,i,0,abs,16);d+=DEF;abs+=16}p.singles.forEach((r,i)=>{def(out,d,i,2,sing[i],r.block.length);d+=DEF});p.lists.forEach((r,i)=>{def(out,d,i,3,lists[i],r.block.length);d+=DEF});p.widgets.forEach((_,i)=>{def(out,d,i,7,abs,20);d+=DEF;abs+=20});for(const r of p.refs){writeU24LE(out,po,r.i);out[po+3]=r.t;writeU16LE(out,po+4,r.e.x);writeU16LE(out,po+6,r.e.y);po+=16}p.widgets.forEach((w,i)=>{data(out,po,w.e.data);out[po+2]=w.e.count??2;out[po+3]=0x10|((w.e.zero?1:0)<<2)|((w.e.align??1)&3);writeU24LE(out,po+8,i);out[po+11]=3;out[po+13]=(w.e.space??0)&255;po+=20});return out}
const resources=(p:ReturnType<typeof prepare>)=>[...p.singles,...p.lists];const resLen=(p:ReturnType<typeof prepare>)=>resources(p).reduce((a,r)=>a+r.block.length,0);
function layout(d:Design,aod=false,background?:Raster):Elem[]{const ds=digits(d,aod),sample=ds[0],clockW=sample.width*2,cy=aod?170:d.clock.y;const es:Elem[]=[...(background&&!aod?[{type:'image' as const,x:0,y:0,src:'custom-background',digits:[background]}]:[]),{type:'num',x:106-clockW,y:cy,digits:ds,count:2,data:'0811',align:1,zero:true,space:-4},{type:'num',x:106,y:cy,digits:ds,count:2,data:'1011',align:1,zero:true,space:-4}];if(!aod){let y=Math.max(330,d.clock.y+d.clock.size+45);if(d.widgets.date){const slash=textRaster('·',18,'700',d.colors.secondary);es.push({type:'num',x:68,y,digits:ds,count:2,data:'1812',align:1,zero:true,space:-2},{type:'image',x:99,y:y+5,src:'dot',digits:[slash]},{type:'num',x:114,y,digits:ds,count:2,data:'1012',align:1,zero:true,space:-2});y+=48}if(d.widgets.steps)es.push({type:'num',x:36,y,digits:ds,count:5,data:'0821',align:0,zero:false,space:-3});if(d.widgets.heartRate)es.push({type:'num',x:104,y,digits:ds,count:3,data:'0822',align:0,zero:false,space:-3});if(d.widgets.battery)es.push({type:'num',x:160,y,digits:ds,count:3,data:'0841',align:0,zero:false,space:-3})}return es}
export function inspect(bin:Uint8Array){if(toHex(bin.subarray(0,4))!=='5aa53412')throw Error('Magic inválido');const faces=Math.max(1,readU16LE(bin,0x1c)),id=readNullTerminated(bin,0x28,9),name=readNullTerminated(bin,0x68,60),warnings:string[]=[];if(readU32LE(bin,0x20)>=bin.length)warnings.push('Preview fuera del archivo');for(let f=0;f<faces;f++){const h=MAIN+f*FACE;for(const o of [8,0x18,0x20,0x28,0x40,0x48,0x50]){const c=readU32LE(bin,h+o),p=readU32LE(bin,h+o+4);if(c&&p+c*16>bin.length)warnings.push(`Tabla fuera del archivo (cara ${f})`)}}return{id,name,faces,bytes:bin.length,warnings}}
export function freshId(){const a=new Uint32Array(2);crypto.getRandomValues(a);return String((a[0]*0x100000000+a[1])%900000000+100000000).slice(0,9)}
export function pack(d:Design,id=freshId(),background?:Raster){const normal=prepare(layout(d,false,background)),has=d.aod,aod=has?prepare(layout(d,true)):undefined,fc=has?2:1,headers=MAIN+fc*FACE,nDef=headers,nProp=nDef+normal.definition,prev=encodeImage(preview(d)),prevOff=nProp+normal.property,nRes=prevOff+prev.length,nSingle=offsets(normal.singles,nRes),nLists=offsets(normal.lists,nRes+normal.singles.reduce((a,r)=>a+r.block.length,0)),nData=faceData(normal,nProp,nSingle,nLists);let aDef=0,aData:Uint8Array|undefined;if(aod){aDef=nRes+resLen(normal);const ap=aDef+aod.definition,ar=ap+aod.property,as=offsets(aod.singles,ar),al=offsets(aod.lists,ar+aod.singles.reduce((a,r)=>a+r.block.length,0));aData=faceData(aod,ap,as,al)}const mh=new Uint8Array(MAIN);mh.set([0x5a,0xa5,0x34,0x12]);writeU32LE(mh,0x10,0x800);writeU16LE(mh,0x1c,fc);writeU16LE(mh,0x1e,fc>1?fc+2:1);writeU32LE(mh,0x20,prevOff);writeFixedString(mh,0x28,9,id);writeFixedString(mh,0x68,60,d.name);const parts=[mh,head(normal,nDef,prevOff),...(aod?[head(aod,aDef,0)]:[]),nData,prev,...resources(normal).map(r=>r.block),...(aod&&aData?[aData,...resources(aod).map(r=>r.block)]:[])],bin=concat(parts),report=inspect(bin);if(report.id!==id||report.warnings.length)throw Error('Falló la inspección estructural');return{bin,id,report,preview:preview(d),normalGmf:layout(d,false,background),aodGmf:d.aod?layout(d,true):[]}}
