import{clockMetrics,widgetLayout}from'./layout';
import type {Design} from './schema'; import type {Raster} from './imageCodec';
function canvas(w:number,h:number){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
function cropPad(r:Raster,w:number,h:number){const out=new Uint8Array(w*h*4),ox=Math.floor((w-r.width)/2),oy=Math.floor((h-r.height)/2);for(let y=0;y<r.height;y++)for(let x=0;x<r.width;x++){const tx=x+ox,ty=y+oy;if(tx<0||ty<0||tx>=w||ty>=h)continue;const a=(y*r.width+x)*4,b=(ty*w+tx)*4;out.set(r.rgba.subarray(a,a+4),b)}return{rgba:out,width:w,height:h}}
function rgba(c:HTMLCanvasElement):Raster{const x=c.getContext('2d',{willReadFrequently:true})!;return{rgba:new Uint8Array(x.getImageData(0,0,c.width,c.height).data),width:c.width,height:c.height}}
export function solid(color:string,w=212,h=520):Raster{const c=canvas(w,h),x=c.getContext('2d')!;x.fillStyle=color;x.fillRect(0,0,w,h);return rgba(c)}
export function textRaster(text:string,size:number,weight:string,color:string,pad=6):Raster{const probe=canvas(4,4).getContext('2d')!;probe.font=`${weight} ${size}px system-ui`;const m=probe.measureText(text),w=Math.ceil(m.width)+pad*2,h=Math.ceil(size*1.35);const c=canvas(w,h),x=c.getContext('2d')!;x.font=`${weight} ${size}px system-ui`;x.textBaseline='middle';x.textAlign='center';x.fillStyle=color;x.fillText(text,w/2,h/2);return rgba(c)}
export function digits(d:Design,aod=false){const color=aod?'#f0eee8':d.colors.primary,size=aod?58:d.clock.size,raw=[...'0123456789-'].map(v=>textRaster(v,size,d.clock.weight,color,2)),w=Math.max(...raw.map(r=>r.width)),h=Math.max(...raw.map(r=>r.height));return raw.map(r=>cropPad(r,w,h))}
export function preview(d:Design,aod=false){const c=canvas(212,520),x=c.getContext('2d')!;x.fillStyle=aod?'#000':d.colors.background;x.fillRect(0,0,212,520);x.fillStyle=aod?'#eee':d.colors.primary;const clock=clockMetrics(d,aod);x.font=`${d.clock.weight} ${clock.size}px system-ui`;x.textAlign='center';x.textBaseline='top';x.fillText('10:09',clock.centerX,clock.top);if(!aod){x.fillStyle=d.colors.secondary;x.font='600 16px system-ui';x.textBaseline='alphabetic';let y=widgetLayout(d).dateTop+16;if(d.widgets.date)x.fillText('DOM · 20 SEP',106,y);y+=42;const bits=[];if(d.widgets.steps)bits.push('8.642 pasos');if(d.widgets.heartRate)bits.push('72 ppm');if(d.widgets.battery)bits.push('84%');x.font='600 13px system-ui';bits.forEach((t,i)=>x.fillText(t,106,y+i*30))}return rgba(c)}
